### ISSUE TITLE
Copy to clipboard

### ISSUE THREAD

**Issue by Alex-CodeLab** [Alex-CodeLab/passwordmanager#1]
1. `lookup()`  Default should be to copy the password to clipboard,  instead of printing the `password` to the terminal.  
2. Then, after 30seconds, remove it from the clipboard.
3. add `-p` argument to print to terminal anyway

`pyperclip` seems to be the right tool for this.

**Comment by yuriy-os** [comment]
Hi! I can help you with this issue!

**Comment by yuriy-os** [comment]
I don't think that it is possible to clean clipboard after 30 seconds because your password manager works like script - it runs only once, and after saving or retrieving data from the database, it stops executing. So there is no way to run a background task for cleaning clipboard because there is no "background" to run it on.

**Comment by yuriy-os** [comment]
As to the copying password to the clipboard - I've done it, going to make PR soon.

**Comment by Alex-CodeLab** [comment]
@yuriy-os 
Good point, I did not think about that. 
Leave it out for now.

I know perhaps a way to do it using a background process, but that gets a lot more complicated, so should be a different pr.
